import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Is it worthy?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="lemonade">
      <head>
        <link
          rel="icon"
          href="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor'><path stroke-linecap='round' stroke-linejoin='round' d='m4.5 12.75 6 6 9-13.5'/></svg>"
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
